export const LOGIN_RECEIVE_AUTHENTICATION_URL = 'LOGIN_RECEIVE_AUTHENTICATION_URL';
export const LOGIN_RECEIVE_USER = 'LOGIN_RECEIVE_USER';

export const SEARCH_RECEIVE_SEARCH_SUGGESTIONS = 'SEARCH_RECEIVE_SEARCH_SUGGESTIONS';

export const SESSION_RECEIVE_RECOMMENDATIONS = 'SESSION_RECEIVE_RECOMMENDATIONS';
export const SESSION_RECEIVE_AUDIO_FEATURES = 'SESSION_RECEIVE_AUDIO_FEATURES';

export const PLAYLIST_ADD_TRACK = 'PLAYLIST_ADD_TRACK';
export const PLAYLIST_REMOVE_TRACK = 'PLAYLIST_REMOVE_TRACK';
export const PLAYLIST_EXPORT = 'PLAYLIST_EXPORT';
